### ISSUE TITLE
Impossible to create block with name 'constructor'

### ISSUE THREAD

**Issue by xoxulin** [enb/enb#221]
If you try to add empty block `common.blocks/constructor/constructor.js` then build will be failed with next error

``` bash
TypeError: Cannot call method 'push' of undefined
   at module.exports.inherit._processFile (.../node_modules/enb-bem-techs/lib/levels/level.js:141:44)
   at .../node_modules/enb-bem-techs/lib/levels/level.js:188:23
   at Array.forEach (native)
   at module.exports.inherit._loadElement (.../node_modules/enb-bem-techs/lib/levels/level.js:174:53)
   at .../node_modules/enb-bem-techs/lib/levels/level.js:215:27
   at Array.forEach (native)
   at module.exports.inherit.load (.../node_modules/enb-bem-techs/lib/levels/level.js:212:52)
   at .../node_modules/enb-bem-techs/techs/levels.js:126:38
   at Array.map (native)
   at .../node_modules/enb-bem-techs/techs/levels.js:125:42
```

May be there are many cases of blocks names, which are not valid or reserved?

**Comment by blond** [comment]
Bug in `enb-bem-techs` package: https://github.com/enb/enb-bem-techs/issues/189
